[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.fileinfo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Packages.composer", "nodejs_20", "nginx"]

[phases.build]
cmds = [
    "npm install",
    "npm run build",
    "composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "sh docker/entrypoint.sh"
